control_panel_app/urls.py
__author__ = 'PerminovMA@live.ru'

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, url
from django.views.generic import TemplateView


urlpatterns = patterns('',
                       url(r'^$', 'control_panel_app.views.views.index_page', name='index_url'),

                       url(r'^login$', 'control_panel_app.views.views_authorization.login_page', name='login_url'),
                       url(r'^logout$', 'control_panel_app.views.views_authorization.logout_view', name='logout_url'),

                       url(r'^clients', TemplateView.as_view(template_name='control_panel_app/pages/clients.html'),
                           name='clients_url'),
                       url(r'^offers', TemplateView.as_view(template_name='control_panel_app/pages/offers.html'),
                           name='offers_url'),
                       url(r'^campaigns', TemplateView.as_view(template_name='control_panel_app/pages/campaigns.html'),
                           name='campaigns_url'),
                       url(r'^create_campaign$', 'control_panel_app.views.views.create_campaign_page',
                           name='create_campaign_url'),
                        url(r'^create_offer$', 'control_panel_app.views.views.create_offer_page',
                           name='create_offer_url'),
                       url(r'^edit_campaign/(?P<campaign_id>\d+)/$', 'control_panel_app.views.views.edit_campaign_page',
                           name='edit_campaign_url'),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meedl/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'meedl_core_app.views.index', name='index'),

    url(r'^core/', include('meedl_core_app.urls', namespace='meedl_core', app_name='meedl_core_app')),

    url(r'^control_panel/', include('control_panel_app.urls', namespace='control_panel', app_name='control_panel_app')),

    url(r'^rest_api/', include('meedl_core_app.rest_api.rest_urls', namespace='rest_api', app_name='meedl_core_app')),

    url(r'^admin/', include(admin.site.urls)),
)

control_panel_app/models.py
from django.db import models

# Create your models here.

control_panel_app/forms/authorization_forms.py
__author__ = 'PerminovMA@live.ru'

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput)

control_panel_app/forms/create_forms.py
__author__ = 'PerminovMA@live.ru'

from django.forms import ModelForm, ValidationError, BooleanField
from meedl_core_app.models import AdvCampaign, Offer


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ['name', 'client', 'offer_url', 'revenue_per_lead', 'currency_type', 'limit_number_leads',
                  'use_sub_id']

    def clean_revenue_per_lead(self):
        revenue = self.cleaned_data.get('revenue_per_lead')

        if revenue is not None:
            if revenue < 0:
                raise ValidationError("Revenue_per_lead must be positive!", code="incorrect_data")
        else:
            raise ValidationError("Internal Error! Unable to get revenue_per_lead.", code="internal_error")

        return revenue

    def clean_use_sub_id(self):
        use_sub_id = self.cleaned_data.get('use_sub_id')
        client = self.cleaned_data.get('client')
        offer_url = self.cleaned_data.get('offer_url')

        if use_sub_id:
            if not offer_url:
                raise ValidationError("please, fill the offer url field", code="warning")

            if client:
                cpa_network = client.cpa_network
                if not cpa_network:
                    raise ValidationError("CPA network doesn't use for the Client of this Offer", code="warning")
                if cpa_network.sub_id_is_added(offer_url):
                    raise ValidationError("sub_id already added in offer_url", code="warning")
            else:
                raise ValidationError("please, choose client", code="warning")

        return use_sub_id


class AdvCampaignForm(ModelForm):
    class Meta:
        model = AdvCampaign
        fields = ['name', 'adv_platform', 'direction', 'campaign_cost', 'offer']

    def clean_campaign_cost(self):
        cost = self.cleaned_data.get('campaign_cost')

        if cost is not None:
            if cost < 0:
                raise ValidationError("Campaign cost must be positive!", code="incorrect_data")
        else:
            raise ValidationError("Internal Error! Unable to get campaign_cost.", code="internal_error")

        return cost

    def clean_offer(self):
        offer = self.cleaned_data.get('offer')
        if offer:
            if not offer.is_active:
                raise ValidationError("It's offer is not active!", code="relation_object_not_active")
        else:
            raise ValidationError("Internal Error! Unable to get offer.", code="internal_error")

        return offer

control_panel_app/forms/detail_forms.py
__author__ = 'PerminovMA@live.ru'

from django.forms import ModelForm, ValidationError
from meedl_core_app.models import AdvCampaign
from django.forms import TextInput, CharField


class DetailAdvCampaignForm(ModelForm):
    tracking_url = CharField(label="tracking url", required=False,
                             widget=TextInput(attrs={'size': '50rem;', 'readonly': True}))

    class Meta:
        model = AdvCampaign
        fields = ['name', 'adv_platform', 'direction', 'campaign_cost', 'offer', 'is_active', 'count_clicks',
                  'count_leads', 'offer_url', 'tracking_url']
        widgets = {
            'offer_url': TextInput(attrs={'readonly': True, 'size': '50rem;'}),
        }
        labels = {
            'offer_url': "offer URL",
        }

    def clean_campaign_cost(self):
        cost = self.cleaned_data.get('campaign_cost')

        if cost is not None:
            if cost < 0:
                raise ValidationError("Campaign cost must be positive!", code="incorrect_data")
        else:
            raise ValidationError("Internal Error! Unable to get campaign_cost.", code="internal_error")

        return cost

control_panel_app/views/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from control_panel_app.forms.create_forms import AdvCampaignForm, OfferForm
from control_panel_app.forms.detail_forms import DetailAdvCampaignForm
from meedl_core_app.models import AdvCampaign
from django.core.urlresolvers import reverse


@login_required()
def index_page(request):
    context = {}
    return render(request, 'control_panel_app/control_panel_main.html', context)


@login_required()
def create_offer_page(request):
    title_page = "Create offer"
    form_action_url = reverse("control_panel:create_offer_url")

    if request.method == "POST":
        form = OfferForm(request.POST)

        if form.is_valid():
            new_campaign = form.save()
            context = {"created_object": new_campaign, 'title': title_page, 'action_url': form_action_url}
            return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html', context)
        else:
            return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html',
                          {'form': form, "title": title_page, 'action_url': form_action_url})
    else:
        form = OfferForm()
        return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html',
                      {'form': form, 'title': title_page, 'action_url': form_action_url})


@login_required()
def create_campaign_page(request):
    title_page = "Create campaign"
    form_action_url = reverse("control_panel:create_campaign_url")

    if request.method == "POST":
        form = AdvCampaignForm(request.POST)

        if form.is_valid():
            new_campaign = form.save()
            context = {"created_object": new_campaign, 'title': title_page, 'action_url': form_action_url}
            return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html', context)
        else:
            return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html',
                          {'form': form, "title": title_page, 'action_url': form_action_url})
    else:
        form = AdvCampaignForm()
        return render(request, 'control_panel_app/pages/pages_to_create/universal_page_to_create.html',
                      {'form': form, 'title': title_page, 'action_url': form_action_url})


@login_required()
def edit_campaign_page(request, campaign_id):
    campaign = get_object_or_404(AdvCampaign, id=campaign_id)

    if request.method == "POST":
        form = DetailAdvCampaignForm(request.POST, instance=campaign)

        if form.is_valid():
            updated_campaign = form.save()
            context = {"campaign_form": form, "campaign": updated_campaign, "is_updated": True}
            return render(request, 'control_panel_app/edit_campaign.html', context)
        else:
            context = {'campaign_form': form, 'campaign': campaign}
            return render(request, 'control_panel_app/edit_campaign.html', context)
    else:
        form = DetailAdvCampaignForm(instance=campaign)

        tracking_url = form.fields.get('tracking_url')
        if tracking_url:
            tracking_url.initial = campaign.get_tracking_url()  # put text to form textfield

        context = {'campaign_form': form, 'campaign': campaign}
        return render(request, 'control_panel_app/edit_campaign.html', context)

control_panel_app/views/views_authorization.py
__author__ = 'PerminovMA@live.ru'

from django.shortcuts import render, redirect
from control_panel_app.forms.authorization_forms import LoginForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout


def login_page(request):
    if request.user.is_authenticated():
        return redirect('control_panel:index_url')

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            if not username or not password:
                return HttpResponse("Bad request")

            user = authenticate(username = username, password = password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('control_panel:index_url')
                else:
                    context = {'disabled_account': True}
            else:
                print form.cleaned_data
                context = {'access_denied': True}
    else:
        context = {}

    form = LoginForm()
    context["login_form"] = form
    return render(request, 'control_panel_app/login_page.html', context)


def logout_view(request):
    logout(request)
    return redirect('control_panel:login_url')

control_panel_app/templates/control_panel_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html {% block html_tag_attribute %} {% endblock %}>
<head lang="en">
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %} </title>

    <!-- Bootstrap -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    {% block additional_stylesheets %} {% endblock %}

</head>
    <body>

        {% block navbar %} {% endblock %}

        <div class="container">
            {% block body %} {% endblock %}
        </div>

        {% block footer %} {% endblock %}


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static "jquery.min.js" %}"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>


        {% block additional_scripts %} {% endblock %}

    </body>
</html>

control_panel_app/templates/control_panel_app/control_panel_main.html
{% extends "control_panel_app/site_template.html" %}


{% block left_sidebar_items %}

    <ul ng-click="set_active($event)" class="nav nav-sidebar" ng-controller="LeftSidebarController">
        <li><a href="#/">Main page</a></li>
        <li><a href="#/clients">Clients</a></li>
        <li><a href="#/offers">Offers</a></li>
        <li><a href="#/campaigns">Campaigns</a></li>
        <!-- <li><a href="#/create_campaign">Create campaign</a></li> -->
    </ul>

{% endblock %}

{% block body_content %}
    <div ng-view></div>
{% endblock %}

control_panel_app/templates/control_panel_app/create_campaign.html
{% extends "control_panel_app/site_template.html" %}

{% block body %}

    <div class="row" style="padding-top: 10rem;">
        <div class="jumbotron col-md-6 col-md-offset-3">
            <h2 style="text-align: center;">Создание компании</h2>

            <div class="row" style="margin-top: 5rem;">
                {% if campaign_form %}
                    <form role="form" action="{% url 'control_panel:create_campaign_url' %}" method="post">{% csrf_token %}

                        {% for field in campaign_form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="help-block">{{ field.help_text }}</p>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-default">Отправить</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

control_panel_app/templates/control_panel_app/edit_campaign.html
{% extends "control_panel_app/site_template.html" %}

{% block body %}
    <div class="row" style="padding-top: 10rem;">

        {% if is_updated %}
            <p class="bg-success"> Изменения сохранены </p>
        {% endif %}

        {% if campaign_form and campaign %}
            <h2 style="text-align: center;">Кампания {{ campaign.name }}</h2>

            <div>
                <form role="form" action="{% url 'control_panel:edit_campaign_url' campaign.id %}" method="post">{% csrf_token %}
                    {% for field in campaign_form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="help-block">{{ field.help_text }}</p>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-default">Отправить</button>
                </form>
            </div>
        {% endif %}

    </div>
{% endblock %}

control_panel_app/templates/control_panel_app/login_page.html
{% extends "control_panel_app/site_template.html" %}

{% block title %} Control panel main page {% endblock %}

{% block body %}

    <div class="row" style="padding-top: 100px;">

        {% if access_denied %}
            <p>Wrong username or password.</p>
        {% elif disabled_account %}
            <p>You'r account is disabled.</p>
        {% endif %}

        <form action="{% url 'control_panel:login_url' %}" method="post">
            {% csrf_token %}
            {{ login_form }}
            <input type="submit" value="Submit" />
        </form>

    </div>

{% endblock %}

control_panel_app/templates/control_panel_app/site_template.html
{% extends "control_panel_app/base.html" %}
{% load staticfiles %}

{% block html_tag_attribute %}ng-app="control_panel_angular_module"{% endblock %}

{% block title %} meedl control panel {% endblock %}

{% block additional_stylesheets %}
    <!-- Custom styles for this template -->
    <link href="{% static "control_panel_app/css/control_panel.css" %}" rel="stylesheet">
{% endblock %}

{% block additional_scripts %}
    <!-- AngularJS -->
    <script src="{% static "angularjs/angular.min.js" %}"></script>
    <script src="{% static "angularjs/angular-route.min.js" %}"></script>
    <script src="{% static "angularjs/angular-resource.min.js" %}"></script>

    <script src="{% static "control_panel_app/js/angularjs_scripts/control_panel_module.js" %}"></script>
    <script src="{% static "control_panel_app/js/angularjs_scripts/control_panel_router.js" %}"></script>
    <script src="{% static "control_panel_app/js/angularjs_scripts/controllers/clients_controller.js" %}"></script>
    <script src="{% static "control_panel_app/js/angularjs_scripts/controllers/campaigns_controller.js" %}"></script>
    <script src="{% static "control_panel_app/js/angularjs_scripts/controllers/offers_controller.js" %}"></script>
    <script src="{% static "control_panel_app/js/angularjs_scripts/controllers/left_sidebar_controller.js" %}"></script>
{% endblock %}


{% block navbar %}

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'control_panel:index_url' %}">meedl control panel</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#home">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

{% endblock %}

{% block body %}

    <div class="row">

        <!-- left sidebar bar -->
        <div class="col-sm-3 col-md-2 sidebar" id="left_sidebar">
            {% block left_sidebar_items %} {% endblock %}

            <!-- <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Overview</a></li>
                <li><a href="#">Reports</a></li>
                <li><a href="#">Analytics</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
            </ul> -->
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block body_content %}{% endblock %}
        </div>

    </div>

{% endblock %}